config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :categories
  
  resources :markers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :markers, dependent: :delete_all
  has_many :subcategories, :class_name => "Category", :dependent => :destroy
  belongs_to :parent, :class_name => "Category",:foreign_key => 'category_id', optional: true


 
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :category
  belongs_to :type

 
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :markers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    def index
      @category = nil
      @categories = Category.where(category_id: nil)
      @chart = Category.joins(:markers).group(:title).count
      #IceCreams.joins(added_extras: :extra).group('extras.name').count

    end
    
  end

  # GET /categories/1
  # GET /categories/1.json
  # Show subcategory
def show
  
  @category = Category.find(params[:id])
  
  @categories = @category.subcategories
  

  render :action => :index
end


  # GET /categories/new
  def new
    @category = Category.new
    @category.category_id = params[:id] unless params[:id].nil?
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :public, :category_id)
    end

    
      
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.all
    @marker = Marker.new
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    @categories = Category.all
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { render :index, notice: 'Marker was successfully created.' }
        format.json { render :show, status: :created, location: @marker }
        format.js {@marker}
      else
        format.html { render :new }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: 'Marker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:title, :type_id, :category_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%=form.select :category_id, Category.where(category_id: nil).pluck(:title, :id),:prompt => 'Select'%>
  </div>


  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= pie_chart @chart unless @chart.nil?%>

<h1><%= @category.nil? ? 'Marcadores por categoria' : @category.title %></h1>
<table>
<thead>
  <th></th>
</thead>
<% @categories.each do |category| %>
<% if category.public? %>
  
<tr>
  <td><h2><b><%= link_to category.title, category_path(category) %></b></h2></td>
 

  <td><%= link_to 'Edit', edit_category_path(category)  unless @category.nil?%></td>
  <td><%= link_to 'X', category_path(category), :confirm => 'Are you sure?', :method => :delete  unless @category.nil? %></td>
</tr>
   <% category.markers.each do |marker| %> 
  <tr style="">
      <td style= 'color:black;'>
     <li ><%= link_to "#{marker.title}", marker_path(marker), style: 'color:black'%> |
     <%= marker.type.title%></li>
     </td>
  </tr>
    <% end %>
<% end %> 
<% end %>
</table>
<p>
  <%= link_to 'Back', @category.parent.nil? ? categories_path : category_path(@category.parent) unless @category.nil? %>
  <%= link_to 'New category', new_category_path(@category) %>
</p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Public:</strong>
  <%= @category.public %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.parent %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to 'Index', root_path %> |
  <%= link_to 'All markers', markers_path %> |
  <%= link_to "New Marker", new_marker_path%>
  
    <%= yield %>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_with(model: marker, data: {confirm:" Enviar datos ? "}) do |form| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.select :type_id, Type.pluck(:title, :id) %>
  </div>

  

  
  <div class ="field">
    <%= form.grouped_collection_select(:category_id, Category.where(category_id:nil).order(:title), 
                          :subcategories, :title, :id, :title, 
                          include_blank: "Please Choose...") %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/markers/_marker.html.erb
<tr id = >
        <td><%= marker.title %></td>
        <td><%= marker.type.title %></td>
        <td><%= marker.category.title %></td>
        <td><%= link_to 'Show', marker %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
        <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/markers/create.js.erb
$('#markers').append( '<%= j render @marker %> ');
$('#markers.tr').fadeIn('slow');

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Markers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="markers">
   <%= render @markers%>
  </tbody>
</table>

<br>

<%= render 'form', marker: @marker %>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @marker.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @marker.type.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @marker.category.title %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.title %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @type.title %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>